spring.application.name=desafio.itau
server.port=8080
spring.threads.virtual.enabled=true

spring.web.resources.add-mappings=false
spring.mvc.throw-exception-if-no-handler-found=true
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=OFF